import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

import WeChatVConsoleScript from '@/app/components/WeChatVConsoleScript'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://sdk-stg.7app.7eleven.co.th/seff/4.2.0/sdk.js"
          strategy="beforeInteractive"
        />
        <WeChatVConsoleScript />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
